on:
  push:
    branches:
      - 'main'
      - 'homolog'
      - 'develop'
  workflow_dispatch:

name: Standard CI
jobs:
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: yarn install --immutable
      - name: TypeScript
        run: yarn type-check
      - name: Lint
        run: yarn lint-check
      - name: Prettier
        run: yarn prettier-check
      - name: Test
        run: yarn test:coverage
      - name: Build project
        run: echo "Building..." && yarn build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying..."
